# Generated by Django 2.2 on 2021-01-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_And_Registration', '0002_comments_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
