# Generated by Django 2.2 on 2021-01-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_And_Registration', '0004_auto_20210112_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
